stages:
    - deploy
    - webapp

deploy:
    stage: deploy
    script:
        - echo "nothing to do"

pages:
    stage: webapp
    before_script:
        - git clone https://github.com/dbr/tvdb_api.git
        - cp tvdb_api/* public/
        - cp ../epgen.py public/
